function [x_best, Fopt, exitflag, output] = run_ga_driver( ...
    fitnessfcn, LB_int, UB_int, intcon, step_sizes, seed)
%RUN_GA_DRIVER Genetic algorithm configuration and execution procedure.
%
% Inputs:
%   fitnessfcn  - Objective-function handle defined by the process model
%   LB_int      - Lower bounds in the scaled search space
%   UB_int      - Upper bounds in the scaled search space
%   intcon      - Indices of integer-constrained variables
%   step_sizes  - Engineering discretization intervals
%   seed        - Random seed used for the GA run
%
% Outputs:
%   x_best      - Best solution in physical units
%   Fopt        - Minimum objective value
%   exitflag    - GA termination flag
%   output      - GA diagnostic information

nvars = numel(LB_int);

assert(numel(UB_int) == nvars, ...
    'The lower- and upper-bound vectors must have the same length.');

assert(numel(step_sizes) == nvars, ...
    'The step-size vector must match the number of decision variables.');

rng(seed, 'twister');

population_size = 500;

options = optimoptions('ga', ...
    'PopulationSize', population_size, ...
    'CreationFcn', @gacreationuniformint, ...
    'FitnessScalingFcn', @fitscalingrank, ...
    'SelectionFcn', {@selectiontournament, 4}, ...
    'EliteCount', round(population_size * 0.05), ...
    'CrossoverFcn', @crossoverlaplace, ...
    'CrossoverFraction', 0.80, ...
    'MutationFcn', @mutationpower, ...
    'MaxGenerations', 150, ...
    'MaxStallGenerations', 30, ...
    'FunctionTolerance', 1e-8, ...
    'Display', 'iter', ...
    'PlotFcn', @gaplotbestf, ...
    'UseParallel', true);

[x_best_int, Fopt, exitflag, output] = ga( ...
    fitnessfcn, nvars, [], [], [], [], ...
    LB_int, UB_int, [], intcon, options);

x_best = x_best_int .* step_sizes;

end
